### ISSUE TITLE
Produce and Sort List of Instances to be Updated

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-ecs-updater#7]
- [x] List container instances in the cluster that are running Bottlerocket. (https://github.com/bottlerocket-os/bottlerocket-ecs-updater/issues/5)
- [x] Keep only those that need a Bottlerocket update. (Checking this can be done in parallel.) (also https://github.com/bottlerocket-os/bottlerocket-ecs-updater/issues/5)
- [x] Eliminate those that host non-service tasks. (https://github.com/bottlerocket-os/bottlerocket-ecs-updater/issues/8)
- [ ] Sort the list by current version ascending, seed ascending
